name: Check In Actions

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        # Install specific version of UV
        version: "0.9.9"
        enable-cache: true
    
    - name: Set up Python 3.10
      run: uv python install
      
    - name: Install dependencies
      run: uv sync --locked --extra ci -q

    - name: Check with Ruff
      run: |
        uv run ruff check --output-format=github
        
    - name: Test with pytest
      run: |
        uv run pytest -rsx --cov --cov-report term-missing tests/
